#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S3,     gyroSensor,     sensorI2CHiTechnicGyro)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  mtr_S1_C1_1,     blWheel,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     brWheel,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     frWheel,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     spinMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     flWheel,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    launch,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    frontServo,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_3,    backServo,            tServoContinuousRotation)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{
	return;
}

task main()
{
	initializeRobot();

	waitForStart();

	int deadzone = 25;
	int divisor = 1;

	while(true)
	{
		getJoystickSettings(joystick);

		if(joy1Btn(5) == 1)
		{
			divisor = 1;
		}
		else if(joy1Btn(6) == 1)
		{
			divisor = 7;
		}

		if(abs(joystick.joy1_y1) < deadzone)
		{
			joystick.joy1_y1 = 0;
		}
		else
		{
			joystick.joy1_y1 = joystick.joy1_y1;
		}

		if(abs(joystick.joy1_x1) < deadzone)
		{
			joystick.joy1_x1 = 0;
		}
		else
		{
			joystick.joy1_x1 = joystick.joy1_x1;
		}

		if (abs(joystick.joy1_x2) < deadzone)
		{
			joystick.joy1_x2 = 0;
		}
		else
		{
			joystick.joy1_x2 = joystick.joy1_x2;
		}

		// Equations To Allow Omni Movement
		motor[frWheel] = (joystick.joy1_y1 - joystick.joy1_x1 - joystick.joy1_x2) / divisor;
		motor[brWheel] = (joystick.joy1_y1 + joystick.joy1_x1 - joystick.joy1_x2) / divisor;
		motor[flWheel] = (-joystick.joy1_y1 - joystick.joy1_x1 - joystick.joy1_x2) / divisor;
		motor[blWheel] = (-joystick.joy1_y1 + joystick.joy1_x1 - joystick.joy1_x2) / divisor;

		// Launch Servo
		if(joy2Btn(2))
		{
			servo[servo1] = 250;
		}
		else if(joy2Btn(3))
		{
			servo[servo1] = 100;
		}
		else
		{
			servo[servo1] = 40;
		}

		// Spin Arm
		if(joy2Btn(6))
		{
			motor[spinMotor] = 150;
		}
		else if(joy2Btn(8))
		{
			motor[spinMotor] = 0;
		}

		// Tube Base Hooks
		if(joystick.joy2_y1 > deadzone)
		{
			servo[servo2] = 255;
		}
		else if(joystick.joy2_y1 < -deadzone)
		{
			servo[servo2] = 0;
		}
		else if(joystick.joy2_y2 > deadzone)
		{
			servo[servo3] = 0;
		}
		else if(joystick.joy2_y2 < -deadzone)
		{
			servo[servo3] = 255;
		}
		else
		{
			servo[servo2] = 127;
			servo[servo3] = 127;
		}
	}
}
